### ISSUE TITLE
didn't have any blocks in api /blocks

### ISSUE THREAD

**Issue by dmitrich777-2** [mining-pool/open-grin-pool#36]
Hello!  Have a many questions. Firstly a problem with pool blocks. Epic node was found a couple of blocks, but pool didn't have it on the api json. Also revenue value of miner page is zero. Have a question with that. Which name should be in miner? MinerName.RigName or MinerName only? When I set a name without .rig I have a workers changed randomly for each worker in the /miner api. When I'm setting a .rig I have a separate page for each rig. But I have many rigs so I should set a paying password for each? Could you update a html and js files for compatibility with new /blocks api?

**Comment by maoxs2** [comment]
I have failed test code on their [new daemon on windows](https://d1ftoepmu0es39.cloudfront.net/epic-server-2.8.0.zip), because the daemon flash exit without any message, so I have put the updated code in https://github.com/maoxs2/open-grin-pool/tree/untest branch.

Then let me explain some details.

Payment module is half-done which dones't support autosend.

There are 3 parameters for the miner: login, pass, and agent. Login is the MinerName. Pass is the payment password, ("x" is also treated as no password), which is saved in plaintext in redis so maintainer can manually update it. Agent is treat as the rig name, and if it is empty, it will be granted with a random name in pool `agent = "NoNameMiner" + strconv.FormatInt(rand.Int63(), 10)`.

This repo will be intergrated into https://github.com/mining-pool and follow [new api standard](https://github.com/mining-pool/mining-pool-api), so it wont be significantly updated.

**Comment by C0MM4ND** [comment]
Solved and Tested #38
